<a href="https://colab.research.google.com/github/mehmetsar/DA_assignments/blob/main/Statistics_Assignment_2_ipynb_adl%C4%B1_not_defterinin_kopyas%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [78]:
import numpy as np
import pandas as pd
from scipy import stats as stats


 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [22]:
samples = np.random.normal(100, 15, 1000)
samples

array([ 95.49310562,  86.07374403,  67.8746581 ,  88.78500754,
       108.85175117, 109.57661827, 129.44089432,  82.7418749 ,
       105.61032172,  98.45857122,  92.36360609, 110.4630166 ,
       124.624379  , 123.96815961,  97.20242819, 102.09387089,
        97.16320033, 110.54381455,  79.39727836,  91.46842348,
        76.77384487,  95.8143719 ,  98.74613709, 114.8712937 ,
       113.00517936, 105.44100576,  91.76367002, 108.09864579,
        98.87177737, 116.28134139, 102.62197226,  99.97615289,
       100.39077377, 111.45141716,  90.47987979, 116.16946308,
       100.51773616,  95.36105878,  98.07065046, 102.08920415,
        88.83168946, 102.14205375,  91.04159631,  97.60184164,
       112.61725387, 103.74221575, 111.45609795, 108.12597019,
        97.58746053, 107.09375389,  96.15225612, 107.72734954,
       105.06418063, 111.3592526 , 125.02408172, 111.56368897,
       100.42693617,  94.60387152,  82.86125255, 123.67615113,
       104.89485355, 107.18953987,  83.7914529 , 125.38

Compute the **mean**, **median**, and **mode**

In [81]:
mean =samples.mean()
mean
median = np.median(samples)
median
mode = stats.mode(samples)
mode


ModeResult(mode=array([53.85659606]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [44]:
min = np.min(samples) 
max = np.max(samples)
q1  = np.percentile(samples, 25, interpolation = 'midpoint')
q1
q3 = np.percentile(samples, 75, interpolation = 'midpoint')
q3
iqr = q3 - q1

Compute the **variance** and **standard deviation**

In [45]:
variance = np.var(samples)
std_dev = np.std(samples)

Compute the **skewness** and **kurtosis**

In [84]:
skewness = stats.skew(samples)
kurtosis = stats.kurtosis(samples)
print(skewness)
kurtosis

-0.10099532474998028


-0.06933823446731369

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [62]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [73]:
y = np.array(np.linspace(1,10,10))
y

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [75]:
r = r =np.corrcoef(x,y)
r

array([[1., 1.],
       [1., 1.]])

## Pandas Correlation Calculation

Run the code below

In [76]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [16]:
r =np.corrcoef(x,y)
r

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [79]:
rho = stats.spearmanr(x,y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [85]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [86]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [94]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [92]:
np.corrcoef(tips["total_bill"],tips["tip"])

array([[1.        , 0.67573411],
       [0.67573411, 1.        ]])